from flask_restful import Resource
from app.resources.lib import api_response

# TODO: use db object
from collections import namedtuple
Subject = namedtuple("Subject", ["text", "value"])


class SubjectsAPI(Resource):

    def get(self):
        return api_response.success([
            {
                "text": subject.text,
                "value": subject.value
            } for subject in [
                # TODO: store in db
                Subject("Accounting", "accounting"),
                Subject("Advertising", "advertising"),
                Subject("Aged", "aged"),
                Subject("Alcohol", "alcohol"),
                Subject("Animal Welfare", "animal_welfare"),
                Subject("Archaeology", "archaeology"),
                Subject("Architecture", "architecture"),
                Subject("Art and Design", "art_design"),
                Subject("Athletics", "athletics"),
                Subject("Banks and Banking", "banks_banking"),
                Subject("Brooklyn, Borough of", "borough_brooklyn"),
                Subject("Bronx, Borough of the", "borough_bronx"),
                Subject("Brooklyn (City)", "city_brooklyn"),
                Subject("Budget and Finance", "budget_finance"),
                Subject("Building Code", "building_code"),
                Subject("Building Construction", "building_construction"),
                Subject("Buildings", "buildings"),
                Subject("Business", "business"),
                Subject("Celebrations and Parades", "celebrations_parades"),
                Subject("Cemeteries", "cemeteries"),
                Subject("Census", "census"),
                Subject("Charities", "charities"),
                Subject("Children", "children"),
                Subject("City Planning", "city_planning"),
                Subject("Civil Service", "civil_service"),
                Subject("Climate", "climate"),
                Subject("Coastal", "coastal"),
                Subject("Community Relations", "community_relations"),
                Subject("Consumers", "consumers"),
                Subject("Conventions", "conventions"),
                Subject("Correction", "correction"),
                Subject("Cost", "cost"),
                Subject("Courts", "courts"),
                Subject("Crime and Criminals", "crime_criminals"),
                Subject("Criminal Justice", "criminal_justice"),
                Subject("Culture", "culture"),
                Subject("Data and Communications", "data_communications"),
                Subject("Death", "death"),
                Subject("Demography and Population", "demography_population"),
                Subject("Disability", "disability"),
                Subject("Discrimination", "discrimination"),
                Subject("Diseases", "disease"),
                Subject("Drugs", "drugs"),
                Subject("Education", "education"),
                Subject("Education, Bilingual", "education_bilingual"),
                Subject("Education, Pre-kindergarten", "education_prekinder"),
                Subject("Education, Remedial", "education_remedial"),
                Subject("Education, Special", "education_special"),
                Subject("Elections and Voting", "elections_voting"),
                Subject("Electric Power", "electric_power"),
                Subject("Emergencies", "emergencies"),
                Subject("Employment", "employment"),
                Subject("Energy", "energy"),
                Subject("Engineering", "engineering"),
                Subject("Environment", "environment"),
                Subject("Equal Employment", "equal_employment"),
                Subject("Ethics", "ethics"),
                Subject("Ethnic groups", "ethnic_groups"),
                Subject("Families", "families"),
                Subject("Finance", "finance"),
                Subject("Fire Fighting", "fire_fighting"),
                Subject("Firearms", "firearms"),
                Subject("Food", "food"),
                Subject("Food supply", "food_supply"),
                Subject("Fuels", "fuels"),
                Subject("Gambling", "gambling"),
                Subject("Geography", "geography"),
                Subject("Government", "government"),
                Subject("Government - Citizen participation", "government_citizen_participation"),
                Subject("Hazardous Materials", "hazardous_materials"),
                Subject("Health", "health"),
                Subject("History", "history"),
                Subject("Homeless Persons", "homeless_persons"),
                Subject("Hospitals", "hospitals"),
                Subject("Hotels, Taverns, etc.", "hotels"),
                Subject("Housing", "housing"),
                Subject("Housing - Limited Profit", "housing_limited_profit"),
                Subject("Housing - Low Income", "housing_low_income"),
                Subject("Human Rights", "human_rights"),
                Subject("Immigration", "immigration"),
                Subject("Industries", "industries"),
                Subject("Infrastructure", "infrastructure"),
                Subject("Insurance", "insurance"),
                Subject("Internet", "internet"),
                Subject("Islands", "islands"),
                Subject("Labor and Employment", "labor_employment"),
                Subject("Land Use", "land_use"),
                Subject("Landmarks", "landmarks"),
                Subject("Languages", "languages"),
                Subject("Laws and legislation", "laws_legislation"),
                Subject("LGBTQ (Lesbian / Gay / Bisexual / Transgender / Queer or Questioning)", "lgbtq"),
                Subject("Libraries", "libraries"),
                Subject("Licenses and Permits", "licenses_permits"),
                Subject("Manhattan, Borough of", "borough_manhattan"),
                Subject("Maps", "maps"),
                Subject("Markets", "markets"),
                Subject("Mayor (Name)", "mayor_name"),
                Subject("Memorials", "memorials"),
                Subject("Mental Health", "mental_health"),
                Subject("Monuments", "monuments"),
                Subject("Motor Vehicles", "motor_vehicles"),
                Subject("Museums", "museums"),
                Subject("Neighborhoods", "neighborhoods"),
                Subject("Nutrition", "nutrition"),
                Subject("Officials and Employees", "officials_employees"),
                Subject("Parking", "parking"),
                Subject("Parks and Recreation", "parks_recreation"),
                Subject("Pensions", "pensions"),
                Subject("Pests", "pests"),
                Subject("Police", "police"),
                Subject("Police - Community Relations", "police_community_relations"),
                Subject("Police - Discipline", "police_discipline"),
                Subject("Politics and Government", "politics_government"),
                Subject("Pollution", "pollution"),
                Subject("Poverty", "poverty"),
                Subject("Prices", "prices"),
                Subject("Purchasing Methods", "purchasing_methods"),
                Subject("Public Authorities", "public_authorities"),
                Subject("Public Welfare", "public_welfare"),
                Subject("Queens, Borough of", "borough_queens"),
                Subject("Real Property", "real_property"),
                Subject("Records", "records"),
                Subject("Recreation", "recreation"),
                Subject("Recycling", "recycling"),
                Subject("Refuse and Refuse Disposal", "refuse_disposal"),
                Subject("Religions", "religions"),
                Subject("Rent Control", "rent_control"),
                Subject("Rent Stabilization Law", "rent_stabilization_law"),
                Subject("Restaurants", "restaurants"),
                Subject("Retail", "retail"),
                Subject("Rivers", "rivers"),
                Subject("Sanitation", "sanitation"),
                Subject("Schools", "schools"),
                Subject("Schools - Administration", "schools_administration"),
                Subject("Schools - Charter", "schools_charter"),
                Subject("Schools - Parochial", "schools_parochial"),
                Subject("Schools - Private", "schools_private"),
                Subject("Schools - Buildings", "schools_buildings"),
                Subject("Sewage", "sewage"),
                Subject("Small Business", "small_business"),
                Subject("Snow Removal", "snow_removal"),
                Subject("Special Districts", "special_districts"),
                Subject("State of New York", "state_new_york"),
                Subject("Staten Island, Borough of", "borough_staten_island"),
                Subject("Statistics", "statistics"),
                Subject("Statistics, Education", "statistics_education"),
                Subject("Statistics, Police", "statistics_police"),
                Subject("Street Vendors", "street_vendors"),
                Subject("Streets - Maintenance and Repair", "streets_maintenance_repair"),
                Subject("Streets and Highways", "streets_highways"),
                Subject("Students", "students"),
                Subject("Subways", "subways"),
                Subject("Subways - Stations", "subways_stations"),
                Subject("Supplies", "supplies"),
                Subject("Surveying", "surveying"),
                Subject("Taxation", "taxation"),
                Subject("Taxation - Exemption from", "taxation_exemption"),
                Subject("Taxation - Real Property", "taxation_real_property"),
                Subject("Taxicabs", "taxicabs"),
                Subject("Teachers", "teachers"),
                Subject("Television", "television"),
                Subject("Terminals", "terminals"),
                Subject("Terrorism", "terrorism"),
                Subject("Toilets", "toilets"),
                Subject("Tolls", "toils"),
                Subject("Tourists", "tourists"),
                Subject("Traffic and Parking", "traffic_parking"),
                Subject("Traffic Safety", "traffic_safety"),
                Subject("Transit", "transit"),
                Subject("Transit - Rapid", "transit_rapid"),
                Subject("Transportation", "transportation"),
                Subject("Transportation - Finance", "transportation_finance"),
                Subject("Transportation - School", "transportation_school"),
                Subject("Transportation- Planning", "transportation_planning"),
                Subject("Trees", "trees"),
                Subject("Trusts and Estates", "trusts_estates"),
                Subject("Universities and Colleges", "universities_colleges"),
                Subject("Vendors and Contracts", "vendors_contracts"),
                Subject("Veterans", "veterans"),
                Subject("Volunteers", "volunteers"),
                Subject("Water", "water"),
                Subject("Water Supply", "water_supply"),
                Subject("Weapons", "weapons"),
                Subject("Weather", "weather"),
                Subject("Women", "women"),
                Subject("World Trade Center", "world_trade_center"),
                Subject("Youth", "youth")
            ]
        ])
